const menu_data = [
  {
    id:1,
    mega_menu:false,
    has_dropdown:false,
    title:'Inicio',
    link:'/',
  },
  {
    id:2,
    mega_menu:false,
    has_dropdown:false,
    title:'Acerca',
    link:'/about',
  },
  {
    id:3,
    mega_menu:false,
    has_dropdown:false,
    title:'Servicios',
    link:'/service-1',
  },
  {
    id:4,
    mega_menu:false,
    has_dropdown:false,
    title:'Precios',
    link:'/price',
  },
  {
    id:5,
    mega_menu:false,
    has_dropdown:false,
    title:'Contacto',
    link:'/contact',
  }
]
export default menu_data;

